version: '3.9'
services:
  db:
    image: postgres:14.3
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  bot:
    build:
      context: '.'
      dockerfile: Dockerfile
    command: python main.py
    restart: always
    depends_on:
      - db
volumes:
  postgres_data:
